# Lithos database Structure file
# Divided in 4 areas, including the Schema Area
#
b C:\PeWkSpaces\pedb\Lithos\Lithos.b1
#
#
d "Schema Area":6,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos.d1 
#
d "Config_dat":7,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_7.d1 f 320
d "Config_dat":7,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_7.d2
#
d "Config_idx":8,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_8.d1 f 320
d "Config_idx":8,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_8.d2
#
d "Users_dat":9,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_9.d1 f 320
d "Users_dat":9,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_9.d2
#
d "Users_idx":10,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_10.d1 f 320
d "Users_idx":10,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_10.d2
#
d "Functions_dat":11,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_11.d1 f 320
d "Functions_dat":11,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_11.d2
#
d "Functions_idx":12,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_12.d1 f 320
d "Functions_idx":12,32;1 C:\PeWkSpaces\pedb\Lithos\Lithos_12.d2
#
